"""phase-4a: extraction_jobs

Revision ID: 2401f4a8d84b
Revises: 7d2e9a8b3c14
Create Date: 2026-04-25 17:28:36.483609

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2401f4a8d84b"
down_revision: Union[str, Sequence[str], None] = "7d2e9a8b3c14"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "extraction_jobs",
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("callback_url", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("body_code", sa.String(length=16), nullable=True),
        sa.Column("body_verdict", sa.String(length=16), nullable=True),
        sa.Column("attachments_json", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("webhook_attempts", sa.Integer(), nullable=False),
        sa.Column("webhook_delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('PENDING','PROCESSING','COMPLETED','FAILED')",
            name="ck_extraction_jobs_status",
        ),
        sa.PrimaryKeyConstraint("job_id"),
        schema="pii",
    )
    op.create_index(
        op.f("ix_pii_extraction_jobs_request_id"),
        "extraction_jobs",
        ["request_id"],
        unique=False,
        schema="pii",
    )
    op.create_index(
        op.f("ix_pii_extraction_jobs_status"),
        "extraction_jobs",
        ["status"],
        unique=False,
        schema="pii",
    )
    op.drop_constraint(
        op.f("pii_pattern_history_pattern_id_fkey"), "pii_pattern_history", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "pii_pattern_history",
        "pii_patterns",
        ["pattern_id"],
        ["id"],
        source_schema="pii",
        referent_schema="pii",
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "pii_pattern_history", schema="pii", type_="foreignkey")
    op.create_foreign_key(
        op.f("pii_pattern_history_pattern_id_fkey"),
        "pii_pattern_history",
        "pii_patterns",
        ["pattern_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_index(op.f("ix_pii_extraction_jobs_status"), table_name="extraction_jobs", schema="pii")
    op.drop_index(
        op.f("ix_pii_extraction_jobs_request_id"), table_name="extraction_jobs", schema="pii"
    )
    op.drop_table("extraction_jobs", schema="pii")
    # ### end Alembic commands ###
