"""phase-2b: pattern_history.pattern_id nullable + ON DELETE SET NULL

Revision ID: 281a3d0a1495
Revises: 56924e17cf24
Create Date: 2026-04-25 09:34:58.296511

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "281a3d0a1495"
down_revision: Union[str, Sequence[str], None] = "56924e17cf24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("pii_pattern_history", "pattern_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint(
        op.f("pii_pattern_history_pattern_id_fkey"), "pii_pattern_history", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "pii_pattern_history",
        "pii_patterns",
        ["pattern_id"],
        ["id"],
        source_schema="pii",
        referent_schema="pii",
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "pii_pattern_history", schema="pii", type_="foreignkey")
    op.create_foreign_key(
        op.f("pii_pattern_history_pattern_id_fkey"),
        "pii_pattern_history",
        "pii_patterns",
        ["pattern_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column("pii_pattern_history", "pattern_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
