"""phase-2b: add original_pattern_id to history

Revision ID: 3d16cb2b60e7
Revises: 281a3d0a1495
Create Date: 2026-04-25 09:35:45.786144

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3d16cb2b60e7"
down_revision: Union[str, Sequence[str], None] = "281a3d0a1495"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pii_pattern_history", sa.Column("original_pattern_id", sa.Integer(), nullable=False)
    )
    op.drop_index(op.f("ix_pii_pii_pattern_history_pattern_id"), table_name="pii_pattern_history")
    op.create_index(
        op.f("ix_pii_pii_pattern_history_original_pattern_id"),
        "pii_pattern_history",
        ["original_pattern_id"],
        unique=False,
        schema="pii",
    )
    op.drop_constraint(
        op.f("pii_pattern_history_pattern_id_fkey"), "pii_pattern_history", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "pii_pattern_history",
        "pii_patterns",
        ["pattern_id"],
        ["id"],
        source_schema="pii",
        referent_schema="pii",
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "pii_pattern_history", schema="pii", type_="foreignkey")
    op.create_foreign_key(
        op.f("pii_pattern_history_pattern_id_fkey"),
        "pii_pattern_history",
        "pii_patterns",
        ["pattern_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_index(
        op.f("ix_pii_pii_pattern_history_original_pattern_id"),
        table_name="pii_pattern_history",
        schema="pii",
    )
    op.create_index(
        op.f("ix_pii_pii_pattern_history_pattern_id"),
        "pii_pattern_history",
        ["pattern_id"],
        unique=False,
    )
    op.drop_column("pii_pattern_history", "original_pattern_id")
    # ### end Alembic commands ###
