"""phase-2-init: pii_patterns + history + deny_list

Revision ID: 56924e17cf24
Revises:
Create Date: 2026-04-25 09:28:10.608768

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "56924e17cf24"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pii_deny_list",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("score >= 0 AND score <= 1", name="ck_pii_deny_list_score"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entity_type", "value", name="uq_pii_deny_list_entity_value"),
        schema="pii",
    )
    op.create_index(
        op.f("ix_pii_pii_deny_list_entity_type"),
        "pii_deny_list",
        ["entity_type"],
        unique=False,
        schema="pii",
    )
    op.create_table(
        "pii_patterns",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("pattern_name", sa.String(length=128), nullable=False),
        sa.Column("regex", sa.Text(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("context_words", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("strictness", sa.String(length=8), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "strictness IN ('low','medium','high')", name="ck_pii_patterns_strictness"
        ),
        sa.CheckConstraint("score >= 0 AND score <= 1", name="ck_pii_patterns_score"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entity_type", "pattern_name", name="uq_pii_patterns_entity_name"),
        schema="pii",
    )
    op.create_index(
        op.f("ix_pii_pii_patterns_entity_type"),
        "pii_patterns",
        ["entity_type"],
        unique=False,
        schema="pii",
    )
    op.create_table(
        "pii_pattern_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("pattern_id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("snapshot", sa.Text(), nullable=False),
        sa.Column("changed_by", sa.String(length=64), nullable=False),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "action IN ('INSERT','UPDATE','DELETE')", name="ck_pii_pattern_history_action"
        ),
        sa.ForeignKeyConstraint(["pattern_id"], ["pii.pii_patterns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="pii",
    )
    op.create_index(
        op.f("ix_pii_pii_pattern_history_pattern_id"),
        "pii_pattern_history",
        ["pattern_id"],
        unique=False,
        schema="pii",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_pii_pii_pattern_history_pattern_id"),
        table_name="pii_pattern_history",
        schema="pii",
    )
    op.drop_table("pii_pattern_history", schema="pii")
    op.drop_index(op.f("ix_pii_pii_patterns_entity_type"), table_name="pii_patterns", schema="pii")
    op.drop_table("pii_patterns", schema="pii")
    op.drop_index(
        op.f("ix_pii_pii_deny_list_entity_type"), table_name="pii_deny_list", schema="pii"
    )
    op.drop_table("pii_deny_list", schema="pii")
    # ### end Alembic commands ###
