"""phase_5a_masked_artifacts

Revision ID: 5a885a8844a1
Revises: 2401f4a8d84b
Create Date: 2026-04-25 21:40:08.897907

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5a885a8844a1"
down_revision: Union[str, Sequence[str], None] = "2401f4a8d84b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "masked_artifacts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column("attachment_id", sa.String(length=64), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["pii.extraction_jobs.job_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="pii",
    )
    op.create_index(
        op.f("ix_pii_masked_artifacts_expires_at"),
        "masked_artifacts",
        ["expires_at"],
        unique=False,
        schema="pii",
    )
    op.create_index(
        op.f("ix_pii_masked_artifacts_job_id"),
        "masked_artifacts",
        ["job_id"],
        unique=False,
        schema="pii",
    )
    op.create_index(
        op.f("ix_pii_masked_artifacts_token"),
        "masked_artifacts",
        ["token"],
        unique=True,
        schema="pii",
    )
    op.drop_constraint(
        op.f("pii_pattern_history_pattern_id_fkey"), "pii_pattern_history", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "pii_pattern_history",
        "pii_patterns",
        ["pattern_id"],
        ["id"],
        source_schema="pii",
        referent_schema="pii",
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "pii_pattern_history", schema="pii", type_="foreignkey")
    op.create_foreign_key(
        op.f("pii_pattern_history_pattern_id_fkey"),
        "pii_pattern_history",
        "pii_patterns",
        ["pattern_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_index(
        op.f("ix_pii_masked_artifacts_token"), table_name="masked_artifacts", schema="pii"
    )
    op.drop_index(
        op.f("ix_pii_masked_artifacts_job_id"), table_name="masked_artifacts", schema="pii"
    )
    op.drop_index(
        op.f("ix_pii_masked_artifacts_expires_at"), table_name="masked_artifacts", schema="pii"
    )
    op.drop_table("masked_artifacts", schema="pii")
    # ### end Alembic commands ###
