"""phase-3a: api_keys + api_key_nonces

Revision ID: ff6df8c4d0ad
Revises: 6c1d3f4a5b02
Create Date: 2026-04-25 16:07:39.242497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff6df8c4d0ad'
down_revision: Union[str, Sequence[str], None] = '6c1d3f4a5b02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key_nonces',
    sa.Column('key_id', sa.String(length=64), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key_id', 'nonce'),
    schema='pii'
    )
    op.create_index(op.f('ix_pii_api_key_nonces_used_at'), 'api_key_nonces', ['used_at'], unique=False, schema='pii')
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key_id', sa.String(length=64), nullable=False),
    sa.Column('secret_hash', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('ip_allowlist', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('rate_per_minute', sa.Integer(), nullable=False),
    sa.Column('rate_per_hour', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('rate_per_minute > 0 AND rate_per_hour > 0', name='ck_api_keys_rate_positive'),
    sa.PrimaryKeyConstraint('id'),
    schema='pii'
    )
    op.create_index(op.f('ix_pii_api_keys_key_id'), 'api_keys', ['key_id'], unique=True, schema='pii')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pii_api_keys_key_id'), table_name='api_keys', schema='pii')
    op.drop_table('api_keys', schema='pii')
    op.drop_index(op.f('ix_pii_api_key_nonces_used_at'), table_name='api_key_nonces', schema='pii')
    op.drop_table('api_key_nonces', schema='pii')
    # ### end Alembic commands ###
